// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/service/tables.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/service/tables.go -destination=internal/core/service/mock/mock_table_service.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTableService is a mock of TableService interface.
type MockTableService struct {
	ctrl     *gomock.Controller
	recorder *MockTableServiceMockRecorder
	isgomock struct{}
}

// MockTableServiceMockRecorder is the mock recorder for MockTableService.
type MockTableServiceMockRecorder struct {
	mock *MockTableService
}

// NewMockTableService creates a new mock instance.
func NewMockTableService(ctrl *gomock.Controller) *MockTableService {
	mock := &MockTableService{ctrl: ctrl}
	mock.recorder = &MockTableServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableService) EXPECT() *MockTableServiceMockRecorder {
	return m.recorder
}

// AvailableTables mocks base method.
func (m *MockTableService) AvailableTables() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvailableTables")
	ret0, _ := ret[0].(int)
	return ret0
}

// AvailableTables indicates an expected call of AvailableTables.
func (mr *MockTableServiceMockRecorder) AvailableTables() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvailableTables", reflect.TypeOf((*MockTableService)(nil).AvailableTables))
}

// InitializeTables mocks base method.
func (m *MockTableService) InitializeTables(numTables int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeTables", numTables)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeTables indicates an expected call of InitializeTables.
func (mr *MockTableServiceMockRecorder) InitializeTables(numTables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeTables", reflect.TypeOf((*MockTableService)(nil).InitializeTables), numTables)
}
